In [442]:
import pandas as pd
import numpy as np
import json
import requests
import warnings
warnings.filterwarnings('ignore')

In [297]:
seasons={
         0:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_allstats.json",
         1:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_1_allstats.json",
         2:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_2_allstats.json",
         3:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_3_allstats.json",
         4:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_4_allstats.json",
         5:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_8_allstats.json",
         6:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_26_allstats.json",
         7:"https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_49_allstats.json"
        }

In [298]:
## Fectch all stats data, top 5 teams across various statistics
rows=[]
for key,value in seasons.items():
    print(key,value)
    # Dict of all stats
    data = requests.get(value).json()
    season=key
    for i in data['all_stats']:
        stat=i['stat']
        stat_id=i['stat_id']
        minimum_criteria=i['minimum_criteria']
        stat_type=i['stat_type']
        for d in i['data']:
            if season in (0,6,7):
                rows.append([season,stat,stat_id,stat_type, *list(d.values())[:-1]])
            else:
                rows.append([season,stat,stat_id,stat_type, *list(d.values())])
        
cols=['season','stat','stat_id','stat_type','player_id', 'player_name', 'team_id', 'team_name', 'match_played', 'value', 
      'rank', 'total_defending_points', 'team', 'tackles', 'player', 'position_id', 'position_name']
team_stats_df = pd.DataFrame(rows, columns=cols)

0 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_0_allstats.json
1 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_1_allstats.json
2 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_2_allstats.json
3 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_3_allstats.json
4 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_4_allstats.json
5 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_8_allstats.json
6 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_26_allstats.json
7 https://www.prokabaddi.com/sifeeds/kabaddi/static/json/1_49_allstats.json

In [299]:
team_stats_df

,season,stat,stat_id,stat_type,player_id,player_name,team_id,team_name,match_played,value,rank,total_defending_points,team,tackles,player,position_id,position_name
0,0,Top Raider,5,p,197,Pardeep Narwal,6,PAT,104,1101.00,1,None,PAT,None,None,8,Raider
1,0,Top Raider,5,p,81,Rahul Chaudhari,29,TT,120,943.00,2,None,TT,None,None,8,Raider
2,0,Top Raider,5,p,41,Deepak Niwas Hooda,3,JAI,123,856.00,3,None,JAI,None,None,1,All Rounder
3,0,Top Raider,5,p,26,Ajay Thakur,29,TT,115,790.00,4,None,TT,None,None,8,Raider
4,0,Top Raider,5,p,143,Maninder Singh,4,KOL,79,731.00,5,None,KOL,None,None,8,Raider
5,0,Top Defender,6,p,69,Manjeet Chhillar,29,TT,108,339.00,1,None,TT,None,None,1,All Rounder
6,0,Top Defender,6,p,157,Ravinder Pahal,2,DEL,109,320.00,2,None,DEL,None,None,6,"Defender, right corner"
7,0,Top Defender,6,p,142,Sandeep Narwal,5,MUM,120,296.00,3,None,MUM,None,None,1,All Rounder
8,0,Top Defender,6,p,259,Fazel Atrachali,5,MUM,98,295.00,4,None,MUM,None,None,3,"Defender, left corner"
9,0,Top Defender,6,p,71,Mohit Chhillar,29,TT,109,277.00,5,None,TT,None,None,6,"Defender, right corner"
10,0,Team Successful Raids,13,t,0,None,6,Patna Pirates,131,2066.00,1,None,None,None,None,0,None
11,0,Team Successful Raids,13,t,0,None,8,Telugu Titans,122,1843.00,2,None,None,None,None,0,None
12,0,Team Successful Raids,13,t,0,None,1,Bengaluru Bulls,125,1810.00,3,None,None,None,None,0,None
13,0,Team Successful Raids,13,t,0,None,5,U Mumba,126,1803.00,4,None,None,None,None,0,None
14,0,Team Successful Raids,13,t,0,None,4,Bengal Warriors,125,1786.00,5,None,None,None,None,0,None
15,0,Team Raid,14,t,0,None,6,Patna Pirates,131,5643.00,1,None,None,None,None,0,None
16,0,Team Raid,14,t,0,None,7,Puneri Paltan,126,5379.00,2,None,None,None,None,0,None
17,0,Team Raid,14,t,0,None,1,Bengaluru Bulls,125,5327.00,3,None,None,None,None,0,None
18,0,Team Raid,14,t,0,None,5,U Mumba,126,5312.00,4,None,None,None,None,0,None
19,0,Team Raid,14,t,0,None,4,Bengal Warriors,125,5310.00,5,None,None,None,None,0,None
20,0,Team Successful Tackles,15,t,0,None,5,U Mumba,126,1216.00,1,None,None,None,None,0,None
21,0,Team Successful Tackles,15,t,0,None,6,Patna Pirates,131,1176.00,2,None,None,None,None,0,None
22,0,Team Successful Tackles,15,t,0,None,7,Puneri Paltan,126,1159.00,3,None,None,None,None,0,None
23,0,Team Successful Tackles,15,t,0,None,1,Bengaluru Bulls,125,1086.00,4,None,None,None,None,0,None
24,0,Team Successful Tackles,15,t,0,None,8,Telugu Titans,122,1067.00,5,None,None,None,None,0,None
25,0,Team Successful Raids Per Match,16,t,0,None,6,Patna Pirates,131,15.77,1,None,None,None,None,0,None
26,0,Team Successful Raids Per Match,16,t,0,None,28,Haryana Steelers,64,15.28,2,None,None,None,None,0,None
27,0,Team Successful Raids Per Match,16,t,0,None,29,Tamil Thalaivas,64,15.16,3,None,None,None,None,0,None
28,0,Team Successful Raids Per Match,16,t,0,None,8,Telugu Titans,122,15.11,4,None,None,None,None,0,None
29,0,Team Successful Raids Per Match,16,t,0,None,2,Dabang Delhi K.C.,122,14.61,5,None,None,None,None,0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1490,7,Team DOD Raid Points,135,t,0,None,3,Jaipur Pink Panthers,20,73.00,1,None,None,None,None,0,None
1491,7,Team DOD Raid Points,135,t,0,None,28,Haryana Steelers,19,71.00,2,None,None,None,None,0,None
1492,7,Team DOD Raid Points,135,t,0,None,30,U.P. Yoddha,18,71.00,2,None,None,None,None,0,None
1493,7,Team DOD Raid Points,135,t,0,None,6,Patna Pirates,19,69.00,4,None,None,None,None,0,None
1494,7,Team DOD Raid Points,135,t,0,None,5,U Mumba,19,66.00,5,None,None,None,None,0,None
1495,7,Team All-outs Inflicted,136,t,0,None,2,Dabang Delhi K.C.,20,34.00,1,None,None,None,None,0,None
1496,7,Team All-outs Inflicted,136,t,0,None,4,Bengal Warriors,20,34.00,1,None,None,None,None,0,None
1497,7,Team All-outs Inflicted,136,t,0,None,6,Patna Pirates,19,28.00,3,None,None,None,None,0,None
1498,7,Team All-outs Inflicted,136,t,0,None,28,Haryana Steelers,19,27.00,4,None,None,None,None,0,None
1499,7,Team All-outs Inflicted,136,t,0,None,5,U Mumba,19,26.00,5,None,None,None,None,0,None
1500,7,Team All-outs Conceded,137,t,0,None,7,Puneri Paltan,20,33.00,1,None,None,None,None,0,None
1501,7,Team All-outs Conceded,137,t,0,None,29,Tamil Thalaivas,20,30.00,2,None,None,None,None,0,None
1502,7,Team All-outs Conceded,137,t,0,None,1,Bengaluru Bulls,19,24.00,3,None,None,None,None,0,None
1503,7,Team All-outs Conceded,137,t,0,None,3,Jaipur Pink Panthers,20,23.00,4,None,None,None,None,0,None
1504,7,Team All-outs Conceded,137,t,0,None,6,Patna Pirates,19,23.00,4,None,None,None,None,0,None
1505,7,Player Avg Raid Points,138,p,2296,Naveen Kumar,2,Del,20,12.80,1,None,Del,None,None,8,Raider
1506,7,Player Avg Raid Points,138,p,197,Pardeep Narwal,6,Pat,19,12.79,2,None,Pat,None,None,8,Raider
1507,7,Player Avg Raid Points,138,p,318,Pawan Kumar Sehrawat,1,Ben,19,12.74,3,None,Ben,None,None,8,Raider
1508,7,Player Avg Raid Points,138,p,143,Maninder Singh,4,Kol,20,10.25,4,None,Kol,None,None,8,Raider
1509,7,Player Avg Raid Points,138,p,2026,Siddharth Sirish Desai,8,Hyd,18,9.67,5,None,Hyd,None,None,8,Raider
1510,7,Player Avg Tackle Points,139,p,358,Vishal Bhardwaj,8,Hyd,18,3.39,1,None,Hyd,None,None,9,Defender
1511,7,Player Avg Tackle Points,139,p,2330,Sumit,30,UPY,18,3.39,1,None,UPY,None,None,3,"Defender, left corner"
1512,7,Player Avg Tackle Points,139,p,290,Sandeep Kumar Dhull,3,Jai,20,3.35,3,None,Jai,None,None,3,"Defender, left corner"
1513,7,Player Avg Tackle Points,139,p,259,Fazel Atrachali,5,Mum,19,3.16,4,None,Mum,None,None,3,"Defender, left corner"
1514,7,Player Avg Tackle Points,139,p,621,Baldev Singh,4,Kol,20,2.95,5,None,Kol,None,None,6,"Defender, right corner"
1515,7,Team Avg Points Scored,140,t,0,None,2,Dabang Delhi K.C.,20,31.20,1,None,None,None,None,0,None
1516,7,Team Avg Points Scored,140,t,0,None,4,Bengal Warriors,20,30.90,2,None,None,None,None,0,None
1517,7,Team Avg Points Scored,140,t,0,None,1,Bengaluru Bulls,19,30.73,3,None,None,None,None,0,None
1518,7,Team Avg Points Scored,140,t,0,None,28,Haryana Steelers,19,30.10,4,None,None,None,None,0,None
1519,7,Team Avg Points Scored,140,t,0,None,7,Puneri Paltan,20,29.50,5,None,None,None,None,0,None

In [300]:
match_seasons={
         1:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/1_season.json",
         2:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/2_season.json",
         3:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/3_season.json",
         4:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/4_season.json",
         5:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_8.json",
         6:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_26.json",
         7:"https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_49.json"  
}

In [301]:
rows=[]
for key,value in match_seasons.items():
    print(key,value)
    # Dict of all stats realted to matches
    data = requests.get(value).json()
    season=key
    for i in data['matches']:
        series_id=i['series_id']
        series_name=i['series_name']
        start_date=i['start_date']
        end_date=i['end_date']
        venue_id=i['venue_id']
        venue_name=i['venue_name']
        game_id=i['game_id']
        event_name=i['event_name']
        tour_id=i['tour_id']
        tour_name=i['tour_name']
        event_status_id=i['event_status_id']
        event_status=i['event_status']
        event_sub_status=i['event_sub_status']
        event_stage=i['event_stage']
        event_state=i['event_state']
        winning_margin=i['winning_margin']
        league_code=i['league_code']
        event_duration_left=i['event_duration_left']
        event_group=i['event_group']
        event_is_daynight=i['event_is_daynight']
        for i,team in enumerate(i['participants']):
            if i==0:
                Team1=team['name']
            else:
                Team2=team['name']
        if 'beat' in event_sub_status:
            winners=event_sub_status.split('beat')[0].strip()
            losers=event_sub_status.split('beat')[1].split("(")[0].strip()
            winning_score=event_sub_status.split("(")[1].split("-")[0].strip()
            losing_score=event_sub_status.split("-")[1].split(")")[0].strip() 
        elif 'Beat' in event_sub_status:
            winners=event_sub_status.split('Beat')[0].strip()
            losers=event_sub_status.split('Beat')[1].split("(")[0].strip()
            winning_score=event_sub_status.split("(")[1].split("-")[0].strip()
            losing_score=event_sub_status.split("-")[1].split(")")[0].strip()
        else:
            winners=np.nan
            losers=np.nan
            winning_score=np.nan
            losing_score=np.nan

        rows.append([series_id, series_name, start_date, end_date, venue_id, venue_name, game_id, 
                     event_name, tour_id, tour_name, event_status_id, event_status, event_sub_status, 
                     event_stage, event_state, winning_margin, league_code, event_duration_left, 
                     event_group, event_is_daynight,Team1,Team2,winners, losers, winning_score, losing_score])
        
cols=['series_id', 'series_name', 'start_date', 'end_date', 'venue_id', 'venue_name', 'game_id',
      'event_name', 'tour_id', 'tour_name', 'event_status_id', 'event_status', 'event_sub_status', 
      'event_stage', 'event_state', 'winning_margin', 'league_code', 'event_duration_left', 
      'event_group', 'event_is_daynight','Team1','Team2','winners', 'losers', 'winning_score', 'losing_score']
match_stats_df = pd.DataFrame(rows, columns=cols)

1 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/1_season.json
2 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/2_season.json
3 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/3_season.json
4 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/4_season.json
5 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_8.json
6 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_26.json
7 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/multisport_cache_25_3_pkl_0530_en_49.json

In [302]:
match_stats_df.head()

,series_id,series_name,start_date,end_date,venue_id,venue_name,game_id,event_name,tour_id,tour_name,...,league_code,event_duration_left,event_group,event_is_daynight,Team1,Team2,winners,losers,winning_score,losing_score
0,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T20:00+05:30,2014-07-26T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",1,Match 1,1,"Pro Kabaddi League Season 1, 2014",...,pkl,,,false,U Mumba,Jaipur Pink Panthers,U Mumba,Jaipur Pink Panthers,45,31
1,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T21:00+05:30,2014-07-26T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",2,Match 2,1,"Pro Kabaddi League Season 1, 2014",...,pkl,,,false,Dabang Delhi K.C.,Bengaluru Bulls,Bengaluru Bulls,Dabang Delhi,47,28
2,1,"Pro Kabaddi League Season 1, 2014",2014-07-27T20:00+05:30,2014-07-27T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",3,Match 3,1,"Pro Kabaddi League Season 1, 2014",...,pkl,,,false,Bengaluru Bulls,Puneri Paltan,Bengaluru Bulls,Puneri Paltan,40,37
3,1,"Pro Kabaddi League Season 1, 2014",2014-07-27T21:00+05:30,2014-07-27T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",4,Match 4,1,"Pro Kabaddi League Season 1, 2014",...,pkl,,,false,U Mumba,Bengal Warriors,U Mumba,Bengal Warriors,36,25
4,1,"Pro Kabaddi League Season 1, 2014",2014-07-28T20:00+05:30,2014-07-28T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",5,Match 5,1,"Pro Kabaddi League Season 1, 2014",...,pkl,,,false,Puneri Paltan,Dabang Delhi K.C.,Dabang Delhi,Puneri Paltan,35,31

In [303]:
match_stats_df.shape

(652, 26)

In [304]:
match_stats_df['game_id']=match_stats_df['game_id'].astype('int')

In [305]:
from itertools import chain, starmap

def flatten_json_iterative_solution(dictionary):
    """Flatten a nested json file"""

    def unpack(parent_key, parent_value):
        """Unpack one level of nesting in json file"""
        # Unpack one level only!!!
        
        if isinstance(parent_value, dict):
            for key, value in parent_value.items():
                temp1 = parent_key + '_' + key
                yield temp1, value
        elif isinstance(parent_value, list):
            i = 0 
            for value in parent_value:
                temp2 = parent_key + '_'+str(i) 
                i += 1
                yield temp2, value
        else:
            yield parent_key, parent_value    

            
    # Keep iterating until the termination condition is satisfied
    while True:
        # Keep unpacking the json file until all values are atomic elements (not dictionary or list)
        dictionary = dict(chain.from_iterable(starmap(unpack, dictionary.items())))
        # Terminate condition: not any value in the json file is dictionary or list
        if not any(isinstance(value, dict) for value in dictionary.values()) and \
           not any(isinstance(value, list) for value in dictionary.values()):
            break

    return dictionary

In [306]:
rows=[]
for i in match_stats_df['game_id']:
    if i<1801:
        ## Get the season in which the match was played
        series=match_stats_df[match_stats_df['game_id']==i]['series_id'].unique()[0]
        ## Fetch URL based on season
        if int(series)<9:
            value="https://www.prokabaddi.com/sifeeds/kabaddi/live/json/"+str(i)+"_match.json"
        else:
            value="https://www.prokabaddi.com/sifeeds/kabaddi/live/json/from_venue/"+str(i)+"_match.json"
#         print(i,series)
        
        ##Fetch JSON data from url 
        data = requests.get(value).json()   
        #print(type(data))
        teams=data['teams']
        for key,value in teams.items():
            if key=='team':
                for l in value:
                    for k,v in l.items():
                        team=l['name']
                        if k=='stats':
                            sol=flatten_json_iterative_solution(v)
                            key=['points_total', 'points_all_out', 'points_extras', 'points_declare', 'points_raid_points_total', 
                                  'points_raid_points_touch', 'points_raid_points_raid_bonus', 'points_tackle_points_total', 
                                  'points_tackle_points_capture', 'points_tackle_points_capture_bonus', 'raids_total', 'raids_successful', 
                                  'raids_unsuccessful', 'raids_Empty', 'tackles_total','tackles_successful', 'tackles_unsuccessful', 'all_outs', 
                                  'declare']
                            #print(series,i,team,sol)
                            values = [ sol[x] for x in key]
                            pre=[series,i,team]
                            all_values=pre+values
                            rows.append(all_values)
                    


cols=['series','game_id','Team','points_total', 'points_all_out', 'points_extras', 'points_declare', 'points_raid_points_total', 
      'points_raid_points_touch', 'points_raid_points_raid_bonus', 'points_tackle_points_total', 
      'points_tackle_points_capture', 'points_tackle_points_capture_bonus', 'raids_total','raids_successful', 
      'raids_unsuccessful', 'raids_Empty', 'tackles_total', 'tackles_successful', 'tackles_unsuccessful', 'all_outs', 'declare']

match_det_df=pd.DataFrame(rows,columns=cols)

In [307]:
match_det_df

,series,game_id,Team,points_total,points_all_out,points_extras,points_declare,points_raid_points_total,points_raid_points_touch,points_raid_points_raid_bonus,...,points_tackle_points_capture_bonus,raids_total,raids_successful,raids_unsuccessful,raids_Empty,tackles_total,tackles_successful,tackles_unsuccessful,all_outs,declare
0,1,1,Jaipur Pink Panthers,28,2,0,0,25,22,3,...,0,40,20,10,10,24,1,23,2,0
1,1,1,U Mumba,44,4,0,0,28,23,5,...,0,40,21,4,15,32,10,22,4,0
2,1,2,Bengaluru Bulls,42,6,0,0,23,22,1,...,0,40,18,11,10,21,13,8,6,0
3,1,2,Dabang Delhi K.C.,28,0,0,0,15,8,7,...,0,41,14,17,10,33,11,22,0,0
4,1,3,Bengaluru Bulls,39,4,1,0,20,15,5,...,0,41,14,12,15,26,13,13,4,0
5,1,3,Puneri Paltan,34,2,1,0,20,13,7,...,0,41,13,13,14,25,10,15,2,0
6,1,4,Bengal Warriors,24,0,0,0,17,15,2,...,0,39,15,10,14,25,7,18,0,0
7,1,4,U Mumba,35,2,0,0,24,18,6,...,0,39,19,8,12,24,9,15,2,0
8,1,5,Dabang Delhi K.C.,35,2,0,0,23,18,5,...,0,40,21,5,14,27,10,17,2,0
9,1,5,Puneri Paltan,31,2,0,0,22,17,5,...,0,39,16,10,13,23,5,18,2,0
10,1,6,U Mumba,34,2,0,0,23,10,13,...,0,44,22,7,15,31,9,22,2,0
11,1,6,Telugu Titans,35,4,0,0,24,22,2,...,0,43,20,10,13,17,7,10,4,0
12,1,7,U Mumba,35,4,0,0,22,17,5,...,0,41,17,6,17,23,9,14,4,0
13,1,7,Patna Pirates,32,2,0,0,23,14,9,...,0,41,21,9,11,23,6,17,2,0
14,1,8,Bengaluru Bulls,46,6,0,0,25,24,1,...,0,43,20,7,16,26,15,11,6,0
15,1,8,Bengal Warriors,30,0,0,0,19,11,8,...,0,43,16,15,12,31,7,24,0,0
16,1,9,Jaipur Pink Panthers,46,4,1,0,29,22,7,...,0,44,23,3,18,32,12,20,4,0
17,1,9,Telugu Titans,31,2,1,0,24,20,4,...,0,44,21,12,11,25,3,22,2,0
18,1,10,Dabang Delhi K.C.,39,4,0,0,26,21,5,...,0,44,24,12,8,27,8,19,4,0
19,1,10,Bengal Warriors,40,4,0,0,25,19,6,...,0,45,16,9,20,32,11,21,4,0
20,1,11,Patna Pirates,34,2,1,0,27,23,4,...,0,40,22,5,13,23,4,19,2,0
21,1,11,Telugu Titans,35,2,0,0,27,19,8,...,0,41,22,8,11,28,5,23,2,0
22,1,12,Bengal Warriors,37,2,0,0,26,22,4,...,0,40,17,8,15,29,8,21,2,0
23,1,12,Puneri Paltan,34,4,0,0,22,21,1,...,0,39,15,9,14,30,8,22,4,0
24,1,13,Jaipur Pink Panthers,35,4,0,0,24,17,7,...,0,39,21,3,15,16,7,9,4,0
25,1,13,Patna Pirates,18,0,0,0,14,9,5,...,0,39,14,12,13,20,3,17,0,0
26,1,14,Bengal Warriors,28,0,0,0,22,17,5,...,0,37,17,8,12,30,5,25,0,0
27,1,14,U Mumba,38,4,0,0,26,25,1,...,0,37,20,6,11,25,8,17,4,0
28,1,15,Dabang Delhi K.C.,34,2,0,0,21,19,2,...,0,41,19,11,11,30,9,21,2,0
29,1,15,Telugu Titans,36,2,3,0,22,21,1,...,0,41,19,9,13,28,9,19,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1232,49,1786,U Mumba,31,4,2,0,15,12,3,...,0,40,11,8,21,21,10,11,2,0
1233,49,1786,Gujarat Fortunegiants,25,2,3,0,15,11,4,...,0,40,11,11,18,17,5,12,1,0
1234,49,1787,Jaipur Pink Panthers,40,2,3,0,27,17,10,...,0,45,20,11,14,31,8,23,1,0
1235,49,1787,Bengal Warriors,41,4,1,0,26,23,3,...,0,45,20,8,17,27,10,17,2,0
1236,49,1788,Patna Pirates,34,0,1,0,27,16,11,...,1,43,19,8,16,27,5,22,0,0
1237,49,1788,Haryana Steelers,39,6,1,0,24,22,2,...,0,43,19,6,18,24,8,16,3,0
1238,49,1789,Dabang Delhi K.C.,39,4,3,0,20,16,4,...,0,43,16,11,16,27,12,15,2,0
1239,49,1789,Bengaluru Bulls,39,2,4,0,23,15,8,...,0,42,16,13,13,26,10,16,1,0
1240,49,1790,Telugu Titans,39,2,1,0,29,20,9,...,0,41,22,8,11,25,7,18,1,0
1241,49,1790,Bengal Warriors,40,4,4,0,24,18,6,...,0,41,19,8,14,28,8,20,2,0
1242,49,1791,Jaipur Pink Panthers,43,4,0,0,29,20,9,...,0,40,21,8,11,28,10,18,2,0
1243,49,1791,Puneri Paltan,34,2,1,0,23,18,5,...,0,40,18,10,12,28,8,20,1,0
1244,49,1792,Patna Pirates,39,4,2,0,27,24,3,...,0,41,22,8,11,25,6,19,2,0
1245,49,1792,Dabang Delhi K.C.,43,2,2,0,31,19,12,...,1,42,20,7,15,31,7,24,1,0
1246,49,1793,U Mumba,33,2,1,0,23,15,8,...,0,43,19,10,14,23,7,16,1,0
1247,49,1793,Bengaluru Bulls,35,4,2,0,19,16,3,...,0,43,15,8,20,25,10,15,2,0
1248,49,1794,Jaipur Pink Panthers,31,0,3,0,22,13,9,...,0,45,19,12,14,32,6,26,0,0
1249,49,1794,Telugu Titans,51,6,0,0,33,26,7,...,0,45,23,7,15,25,12,13,3,0
1250,49,1795,Haryana Steelers,30,2,2,0,18,16,2,...,2,46,14,12,20,19,6,13,1,0
1251,49,1795,U.P. Yoddha,37,2,3,0,20,13,7,...,2,46,15,6,25,26,10,16,1,0
1252,49,1796,Gujarat Fortunegiants,50,6,1,0,27,24,3,...,0,42,24,8,10,26,16,10,3,0
1253,49,1796,Tamil Thalaivas,21,0,1,0,13,10,3,...,0,42,11,16,15,31,7,24,0,0
1254,49,1797,Puneri Paltan,40,0,0,0,27,15,12,...,3,42,18,14,10,37,10,27,0,0
1255,49,1797,Dabang Delhi K.C.,60,8,5,0,34,27,7,...,0,43,28,10,5,28,13,15,4,0
1256,49,1798,Haryana Steelers,38,2,2,0,23,18,5,...,1,48,17,11,20,26,10,16,1,0
1257,49,1798,Gujarat Fortunegiants,37,2,4,0,18,16,2,...,2,48,15,12,21,29,11,18,1,0
1258,49,1799,Bengal Warriors,42,6,0,0,28,24,4,...,0,41,22,6,13,23,8,15,3,0
1259,49,1799,Dabang Delhi K.C.,33,2,2,0,23,15,8,...,0,39,21,8,10,30,6,24,1,0
1260,49,1800,Tamil Thalaivas,32,2,3,0,18,16,2,...,0,42,16,10,16,25,9,16,1,0
1261,49,1800,U Mumba,36,2,6,0,21,16,5,...,1,42,20,9,13,22,6,16,1,0

In [312]:
match_det_df.shape

(1262, 22)

In [320]:
md=match_det_df.copy()
md['series']=md['series'].astype('int')
md['game_id']=md['game_id'].astype('int')
md.columns[:2]

Index(['series', 'game_id'], dtype='object')

In [323]:
df_out = md.set_index(['game_id','series',md.groupby(['game_id','series']).cumcount()+1]).unstack().sort_index(level=1, axis=1)
df_out.columns = df_out.columns.map('{0[0]}_{0[1]}'.format)
df_out.reset_index()
df_out.head()

,,Team_1,all_outs_1,declare_1,points_all_out_1,points_declare_1,points_extras_1,points_raid_points_raid_bonus_1,points_raid_points_total_1,points_raid_points_touch_1,points_tackle_points_capture_1,...,points_tackle_points_capture_bonus_2,points_tackle_points_total_2,points_total_2,raids_Empty_2,raids_successful_2,raids_total_2,raids_unsuccessful_2,tackles_successful_2,tackles_total_2,tackles_unsuccessful_2
game_id,series,,,,,,,,,,,,,,,,,,,,,
1,1,Jaipur Pink Panthers,2,0,2,0,0,3,25,22,1,...,0,12,44,15,21,40,4,10,32,22
2,1,Bengaluru Bulls,6,0,6,0,0,1,23,22,13,...,0,13,28,10,14,41,17,11,33,22
3,1,Bengaluru Bulls,4,0,4,0,1,5,20,15,14,...,0,11,34,14,13,41,13,10,25,15
4,1,Bengal Warriors,0,0,0,0,0,2,17,15,7,...,0,9,35,12,19,39,8,9,24,15
5,1,Dabang Delhi K.C.,2,0,2,0,0,5,23,18,10,...,0,7,31,13,16,39,10,5,23,18

In [324]:
df_out.shape

(631, 40)

In [325]:
full_match_stats=pd.merge(match_stats_df,df_out , how='left', left_on=['game_id'], right_on=['game_id'])
full_match_stats.head(2)

,series_id,series_name,start_date,end_date,venue_id,venue_name,game_id,event_name,tour_id,tour_name,...,points_tackle_points_capture_bonus_2,points_tackle_points_total_2,points_total_2,raids_Empty_2,raids_successful_2,raids_total_2,raids_unsuccessful_2,tackles_successful_2,tackles_total_2,tackles_unsuccessful_2
0,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T20:00+05:30,2014-07-26T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",1,Match 1,1,"Pro Kabaddi League Season 1, 2014",...,0.0,12.0,44.0,15.0,21.0,40.0,4.0,10.0,32.0,22.0
1,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T21:00+05:30,2014-07-26T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",2,Match 2,1,"Pro Kabaddi League Season 1, 2014",...,0.0,13.0,28.0,10.0,14.0,41.0,17.0,11.0,33.0,22.0

In [331]:
full_match_stats[~(full_match_stats['event_status']=='Yet to begin') ]
# full_match_stats['event_status'].unique()

,series_id,series_name,start_date,end_date,venue_id,venue_name,game_id,event_name,tour_id,tour_name,...,points_tackle_points_capture_bonus_2,points_tackle_points_total_2,points_total_2,raids_Empty_2,raids_successful_2,raids_total_2,raids_unsuccessful_2,tackles_successful_2,tackles_total_2,tackles_unsuccessful_2
0,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T20:00+05:30,2014-07-26T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",1,Match 1,1,"Pro Kabaddi League Season 1, 2014",...,0.0,12.0,44.0,15.0,21.0,40.0,4.0,10.0,32.0,22.0
1,1,"Pro Kabaddi League Season 1, 2014",2014-07-26T21:00+05:30,2014-07-26T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",2,Match 2,1,"Pro Kabaddi League Season 1, 2014",...,0.0,13.0,28.0,10.0,14.0,41.0,17.0,11.0,33.0,22.0
2,1,"Pro Kabaddi League Season 1, 2014",2014-07-27T20:00+05:30,2014-07-27T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",3,Match 3,1,"Pro Kabaddi League Season 1, 2014",...,0.0,11.0,34.0,14.0,13.0,41.0,13.0,10.0,25.0,15.0
3,1,"Pro Kabaddi League Season 1, 2014",2014-07-27T21:00+05:30,2014-07-27T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",4,Match 4,1,"Pro Kabaddi League Season 1, 2014",...,0.0,9.0,35.0,12.0,19.0,39.0,8.0,9.0,24.0,15.0
4,1,"Pro Kabaddi League Season 1, 2014",2014-07-28T20:00+05:30,2014-07-28T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",5,Match 5,1,"Pro Kabaddi League Season 1, 2014",...,0.0,7.0,31.0,13.0,16.0,39.0,10.0,5.0,23.0,18.0
5,1,"Pro Kabaddi League Season 1, 2014",2014-07-28T21:00+05:30,2014-07-28T21:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",6,Match 6,1,"Pro Kabaddi League Season 1, 2014",...,0.0,7.0,35.0,13.0,20.0,43.0,10.0,7.0,17.0,10.0
6,1,"Pro Kabaddi League Season 1, 2014",2014-07-29T20:00+05:30,2014-07-29T20:40+05:30,5,"DOME@NSCI SVP Stadium, Mumbai",7,Match 7,1,"Pro Kabaddi League Season 1, 2014",...,0.0,7.0,32.0,11.0,21.0,41.0,9.0,6.0,23.0,17.0
7,1,"Pro Kabaddi League Season 1, 2014",2014-07-30T05:30+05:30,2014-07-30T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",8,Match 8,1,"Pro Kabaddi League Season 1, 2014",...,0.0,11.0,30.0,12.0,16.0,43.0,15.0,7.0,31.0,24.0
8,1,"Pro Kabaddi League Season 1, 2014",2014-07-31T05:30+05:30,2014-07-31T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",9,Match 9,1,"Pro Kabaddi League Season 1, 2014",...,0.0,4.0,31.0,11.0,21.0,44.0,12.0,3.0,25.0,22.0
9,1,"Pro Kabaddi League Season 1, 2014",2014-07-31T05:30+05:30,2014-07-31T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",10,Match 10,1,"Pro Kabaddi League Season 1, 2014",...,0.0,11.0,40.0,20.0,16.0,45.0,9.0,11.0,32.0,21.0
10,1,"Pro Kabaddi League Season 1, 2014",2014-08-01T05:30+05:30,2014-08-01T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",11,Match 11,1,"Pro Kabaddi League Season 1, 2014",...,0.0,6.0,35.0,11.0,22.0,41.0,8.0,5.0,28.0,23.0
11,1,"Pro Kabaddi League Season 1, 2014",2014-08-01T05:30+05:30,2014-08-01T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",12,Match 12,1,"Pro Kabaddi League Season 1, 2014",...,0.0,8.0,34.0,14.0,15.0,39.0,9.0,8.0,30.0,22.0
12,1,"Pro Kabaddi League Season 1, 2014",2014-08-02T05:30+05:30,2014-08-02T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",13,Match 13,1,"Pro Kabaddi League Season 1, 2014",...,0.0,4.0,18.0,13.0,14.0,39.0,12.0,3.0,20.0,17.0
13,1,"Pro Kabaddi League Season 1, 2014",2014-08-02T05:30+05:30,2014-08-02T06:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",14,Match 14,1,"Pro Kabaddi League Season 1, 2014",...,0.0,8.0,38.0,11.0,20.0,37.0,6.0,8.0,25.0,17.0
14,1,"Pro Kabaddi League Season 1, 2014",2014-08-03T05:30+05:30,2014-08-03T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",15,Match 15,1,"Pro Kabaddi League Season 1, 2014",...,0.0,9.0,36.0,13.0,19.0,41.0,9.0,9.0,28.0,19.0
15,1,"Pro Kabaddi League Season 1, 2014",2014-08-03T05:30+05:30,2014-08-03T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",16,Match 16,1,"Pro Kabaddi League Season 1, 2014",...,0.0,11.0,31.0,17.0,15.0,40.0,8.0,10.0,28.0,18.0
16,1,"Pro Kabaddi League Season 1, 2014",2014-08-04T05:30+05:30,2014-08-04T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",17,Match 17,1,"Pro Kabaddi League Season 1, 2014",...,0.0,5.0,25.0,14.0,12.0,39.0,12.0,4.0,24.0,20.0
17,1,"Pro Kabaddi League Season 1, 2014",2014-08-04T05:30+05:30,2014-08-04T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",18,Match 18,1,"Pro Kabaddi League Season 1, 2014",...,0.0,9.0,33.0,20.0,17.0,42.0,3.0,8.0,23.0,15.0
18,1,"Pro Kabaddi League Season 1, 2014",2014-08-05T05:30+05:30,2014-08-05T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",19,Match 19,1,"Pro Kabaddi League Season 1, 2014",...,0.0,13.0,43.0,13.0,18.0,40.0,9.0,13.0,24.0,11.0
19,1,"Pro Kabaddi League Season 1, 2014",2014-08-05T05:30+05:30,2014-08-05T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",20,Match 20,1,"Pro Kabaddi League Season 1, 2014",...,0.0,14.0,36.0,15.0,15.0,40.0,10.0,14.0,29.0,15.0
20,1,"Pro Kabaddi League Season 1, 2014",2014-08-06T05:30+05:30,2014-08-06T06:10+05:30,2,"Thyagaraj Sports Complex, Delhi",21,Match 21,1,"Pro Kabaddi League Season 1, 2014",...,0.0,5.0,35.0,3.0,22.0,38.0,13.0,5.0,28.0,23.0
21,1,"Pro Kabaddi League Season 1, 2014",2014-08-07T05:30+05:30,2014-08-07T06:10+05:30,6,"Patliputra Sports Complex, Patna",22,Match 22,1,"Pro Kabaddi League Season 1, 2014",...,0.0,4.0,26.0,15.0,19.0,38.0,4.0,3.0,25.0,22.0
22,1,"Pro Kabaddi League Season 1, 2014",2014-08-08T05:30+05:30,2014-08-08T06:10+05:30,6,"Patliputra Sports Complex, Patna",23,Match 23,1,"Pro Kabaddi League Season 1, 2014",...,0.0,6.0,34.0,11.0,21.0,40.0,8.0,5.0,25.0,20.0
23,1,"Pro Kabaddi League Season 1, 2014",2014-08-08T05:30+05:30,2014-08-08T06:10+05:30,6,"Patliputra Sports Complex, Patna",24,Match 24,1,"Pro Kabaddi League Season 1, 2014",...,0.0,13.0,37.0,8.0,17.0,38.0,13.0,9.0,25.0,16.0
24,1,"Pro Kabaddi League Season 1, 2014",2014-08-09T05:30+05:30,2014-08-09T06:10+05:30,6,"Patliputra Sports Complex, Patna",25,Match 25,1,"Pro Kabaddi League Season 1, 2014",...,0.0,6.0,29.0,13.0,16.0,41.0,12.0,5.0,30.0,25.0
25,1,"Pro Kabaddi League Season 1, 2014",2014-08-09T05:30+05:30,2014-08-09T06:10+05:30,6,"Patliputra Sports Complex, Patna",26,Match 26,1,"Pro Kabaddi League Season 1, 2014",...,0.0,7.0,30.0,17.0,19.0,41.0,5.0,7.0,26.0,19.0
26,1,"Pro Kabaddi League Season 1, 2014",2014-08-10T05:30+05:30,2014-08-10T06:10+05:30,6,"Patliputra Sports Complex, Patna",27,Match 27,1,"Pro Kabaddi League Season 1, 2014",...,0.0,7.0,23.0,15.0,8.0,36.0,13.0,6.0,23.0,17.0
27,1,"Pro Kabaddi League Season 1, 2014",2014-08-10T05:30+05:30,2014-08-10T06:10+05:30,6,"Patliputra Sports Complex, Patna",28,Match 28,1,"Pro Kabaddi League Season 1, 2014",...,0.0,6.0,33.0,11.0,21.0,41.0,9.0,5.0,26.0,21.0
28,1,"Pro Kabaddi League Season 1, 2014",2014-08-12T05:30+05:30,2014-08-12T06:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",29,Match 29,1,"Pro Kabaddi League Season 1, 2014",...,0.0,8.0,41.0,15.0,23.0,44.0,6.0,7.0,28.0,21.0
29,1,"Pro Kabaddi League Season 1, 2014",2014-08-13T05:30+05:30,2014-08-13T06:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",30,Match 30,1,"Pro Kabaddi League Season 1, 2014",...,0.0,9.0,27.0,16.0,15.0,40.0,9.0,9.0,28.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,49,"Pro Kabaddi League Season 7, 2019",2019-09-12T19:30+05:30,2019-09-12T20:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",1770,Match 86,49,Pro Kabaddi League,...,1.0,10.0,36.0,19.0,20.0,45.0,6.0,9.0,25.0,16.0
602,49,"Pro Kabaddi League Season 7, 2019",2019-09-12T20:30+05:30,2019-09-12T21:10+05:30,4,"Netaji Subhash Chandra Bose Indoor Stadium, Ko...",1772,Match 88,49,Pro Kabaddi League,...,1.0,7.0,40.0,11.0,19.0,43.0,13.0,6.0,24.0,18.0
603,49,"Pro Kabaddi League Season 7, 2019",2019-09-14T19:30+05:30,2019-09-14T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1773,Match 89,49,Pro Kabaddi League,...,1.0,8.0,33.0,9.0,15.0,41.0,17.0,7.0,23.0,16.0
604,49,"Pro Kabaddi League Season 7, 2019",2019-09-14T20:30+05:30,2019-09-14T21:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1774,Match 90,49,Pro Kabaddi League,...,1.0,15.0,43.0,20.0,16.0,44.0,8.0,14.0,32.0,18.0
605,49,"Pro Kabaddi League Season 7, 2019",2019-09-15T19:30+05:30,2019-09-15T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1775,Match 91,49,Pro Kabaddi League,...,0.0,5.0,30.0,15.0,16.0,42.0,11.0,5.0,21.0,16.0
606,49,"Pro Kabaddi League Season 7, 2019",2019-09-15T20:30+05:30,2019-09-15T21:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1776,Match 92,49,Pro Kabaddi League,...,1.0,18.0,55.0,14.0,22.0,43.0,7.0,17.0,33.0,16.0
607,49,"Pro Kabaddi League Season 7, 2019",2019-09-16T19:30+05:30,2019-09-16T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1777,Match 93,49,Pro Kabaddi League,...,0.0,8.0,38.0,18.0,16.0,42.0,8.0,8.0,21.0,13.0
608,49,"Pro Kabaddi League Season 7, 2019",2019-09-16T20:30+05:30,2019-09-16T21:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1778,Match 94,49,Pro Kabaddi League,...,0.0,11.0,37.0,13.0,18.0,39.0,8.0,11.0,24.0,13.0
609,49,"Pro Kabaddi League Season 7, 2019",2019-09-18T19:30+05:30,2019-09-18T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1779,Match 95,49,Pro Kabaddi League,...,2.0,9.0,36.0,15.0,16.0,41.0,10.0,7.0,25.0,18.0
610,49,"Pro Kabaddi League Season 7, 2019",2019-09-18T20:30+05:30,2019-09-18T21:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1780,Match 96,49,Pro Kabaddi League,...,1.0,7.0,36.0,9.0,21.0,42.0,12.0,6.0,23.0,17.0
611,49,"Pro Kabaddi League Season 7, 2019",2019-09-19T19:30+05:30,2019-09-19T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1781,Match 97,49,Pro Kabaddi League,...,0.0,5.0,36.0,12.0,21.0,44.0,11.0,5.0,30.0,25.0
612,49,"Pro Kabaddi League Season 7, 2019",2019-09-20T19:30+05:30,2019-09-20T20:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1782,Match 98,49,Pro Kabaddi League,...,0.0,7.0,42.0,15.0,17.0,41.0,9.0,7.0,26.0,19.0
613,49,"Pro Kabaddi League Season 7, 2019",2019-09-20T20:30+05:30,2019-09-20T21:10+05:30,7,"Shree Shiv Chhatrapati Sports Complex, Pune",1783,Match 99,49,Pro Kabaddi League,...,0.0,7.0,38.0,3.0,22.0,39.0,14.0,7.0,23.0,16.0
614,49,"Pro Kabaddi League Season 7, 2019",2019-09-21T19:30+05:30,2019-09-21T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1784,Match 100,49,Pro Kabaddi League,...,0.0,15.0,28.0,18.0,8.0,41.0,15.0,15.0,20.0,5.0
615,49,"Pro Kabaddi League Season 7, 2019",2019-09-21T20:30+05:30,2019-09-21T21:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1785,Match 101,49,Pro Kabaddi League,...,0.0,7.0,22.0,19.0,9.0,42.0,14.0,7.0,20.0,13.0
616,49,"Pro Kabaddi League Season 7, 2019",2019-09-22T19:30+05:30,2019-09-22T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1786,Match 102,49,Pro Kabaddi League,...,0.0,5.0,25.0,18.0,11.0,40.0,11.0,5.0,17.0,12.0
617,49,"Pro Kabaddi League Season 7, 2019",2019-09-22T20:30+05:30,2019-09-22T21:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1787,Match 103,49,Pro Kabaddi League,...,0.0,10.0,41.0,17.0,20.0,45.0,8.0,10.0,27.0,17.0
618,49,"Pro Kabaddi League Season 7, 2019",2019-09-23T19:30+05:30,2019-09-23T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1788,Match 104,49,Pro Kabaddi League,...,0.0,8.0,39.0,18.0,19.0,43.0,6.0,8.0,24.0,16.0
619,49,"Pro Kabaddi League Season 7, 2019",2019-09-23T20:30+05:30,2019-09-23T21:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1789,Match 105,49,Pro Kabaddi League,...,0.0,10.0,39.0,13.0,16.0,42.0,13.0,10.0,26.0,16.0
620,49,"Pro Kabaddi League Season 7, 2019",2019-09-25T19:30+05:30,2019-09-25T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1790,Match 106,49,Pro Kabaddi League,...,0.0,8.0,40.0,14.0,19.0,41.0,8.0,8.0,28.0,20.0
621,49,"Pro Kabaddi League Season 7, 2019",2019-09-25T20:30+05:30,2019-09-25T21:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1791,Match 107,49,Pro Kabaddi League,...,0.0,8.0,34.0,12.0,18.0,40.0,10.0,8.0,28.0,20.0
622,49,"Pro Kabaddi League Season 7, 2019",2019-09-26T19:30+05:30,2019-09-26T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1792,Match 108,49,Pro Kabaddi League,...,1.0,8.0,43.0,15.0,20.0,42.0,7.0,7.0,31.0,24.0
623,49,"Pro Kabaddi League Season 7, 2019",2019-09-27T19:30+05:30,2019-09-27T20:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1793,Match 109,49,Pro Kabaddi League,...,0.0,10.0,35.0,20.0,15.0,43.0,8.0,10.0,25.0,15.0
624,49,"Pro Kabaddi League Season 7, 2019",2019-09-27T20:30+05:30,2019-09-27T21:10+05:30,3,"Sawai Mansingh Stadium, Jaipur",1794,Match 110,49,Pro Kabaddi League,...,0.0,12.0,51.0,15.0,23.0,45.0,7.0,12.0,25.0,13.0
625,49,"Pro Kabaddi League Season 7, 2019",2019-09-28T19:30+05:30,2019-09-28T20:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1795,Match 111,49,Pro Kabaddi League,...,2.0,12.0,37.0,25.0,15.0,46.0,6.0,10.0,26.0,16.0
626,49,"Pro Kabaddi League Season 7, 2019",2019-09-28T20:30+05:30,2019-09-28T21:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1796,Match 112,49,Pro Kabaddi League,...,0.0,7.0,21.0,15.0,11.0,42.0,16.0,7.0,31.0,24.0
627,49,"Pro Kabaddi League Season 7, 2019",2019-09-29T19:30+05:30,2019-09-29T20:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1797,Match 113,49,Pro Kabaddi League,...,0.0,13.0,60.0,5.0,28.0,43.0,10.0,13.0,28.0,15.0
628,49,"Pro Kabaddi League Season 7, 2019",2019-09-29T20:30+05:30,2019-09-29T21:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1798,Match 114,49,Pro Kabaddi League,...,2.0,13.0,37.0,21.0,15.0,48.0,12.0,11.0,29.0,18.0
629,49,"Pro Kabaddi League Season 7, 2019",2019-09-30T19:30+05:30,2019-09-30T20:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1799,Match 115,49,Pro Kabaddi League,...,0.0,6.0,33.0,10.0,21.0,39.0,8.0,6.0,30.0,24.0
630,49,"Pro Kabaddi League Season 7, 2019",2019-09-30T20:30+05:30,2019-09-30T21:10+05:30,25,"Tau Devilal Sports Complex, Panchkula",1800,Match 116,49,Pro Kabaddi League,...,1.0,7.0,36.0,13.0,20.0,42.0,9.0,6.0,22.0,16.0

In [332]:
final=full_match_stats.copy()

In [334]:
final.columns

Index(['series_id', 'series_name', 'start_date', 'end_date', 'venue_id',
       'venue_name', 'game_id', 'event_name', 'tour_id', 'tour_name',
       'event_status_id', 'event_status', 'event_sub_status', 'event_stage',
       'event_state', 'winning_margin', 'league_code', 'event_duration_left',
       'event_group', 'event_is_daynight', 'Team1', 'Team2', 'winners',
       'losers', 'winning_score', 'losing_score', 'Team_1', 'all_outs_1',
       'declare_1', 'points_all_out_1', 'points_declare_1', 'points_extras_1',
       'points_raid_points_raid_bonus_1', 'points_raid_points_total_1',
       'points_raid_points_touch_1', 'points_tackle_points_capture_1',
       'points_tackle_points_capture_bonus_1', 'points_tackle_points_total_1',
       'points_total_1', 'raids_Empty_1', 'raids_successful_1',
       'raids_total_1', 'raids_unsuccessful_1', 'tackles_successful_1',
       'tackles_total_1', 'tackles_unsuccessful_1', 'Team_2', 'all_outs_2',
       'declare_2', 'points_all_out_2', 'points_declare_2', 'points_extras_2',
       'points_raid_points_raid_bonus_2', 'points_raid_points_total_2',
       'points_raid_points_touch_2', 'points_tackle_points_capture_2',
       'points_tackle_points_capture_bonus_2', 'points_tackle_points_total_2',
       'points_total_2', 'raids_Empty_2', 'raids_successful_2',
       'raids_total_2', 'raids_unsuccessful_2', 'tackles_successful_2',
       'tackles_total_2', 'tackles_unsuccessful_2'],
      dtype='object')

In [623]:
final_df = final.loc[(final['event_status']=='Match Completed')&(final['event_sub_status'].str.lower().str.contains("beat"))][['Team1', 'Team2', 'winners','winning_margin','all_outs_1',
       'declare_1', 'points_all_out_1', 'points_declare_1', 'points_extras_1',
       'points_raid_points_raid_bonus_1', 'points_raid_points_total_1',
       'points_raid_points_touch_1', 'points_tackle_points_capture_1',
       'points_tackle_points_capture_bonus_1', 'points_tackle_points_total_1',
       'points_total_1', 'raids_Empty_1', 'raids_successful_1',
       'raids_total_1', 'raids_unsuccessful_1', 'tackles_successful_1',
       'tackles_total_1', 'tackles_unsuccessful_1', 'all_outs_2',
       'declare_2', 'points_all_out_2', 'points_declare_2', 'points_extras_2',
       'points_raid_points_raid_bonus_2', 'points_raid_points_total_2',
       'points_raid_points_touch_2', 'points_tackle_points_capture_2',
       'points_tackle_points_capture_bonus_2', 'points_tackle_points_total_2',
       'points_total_2', 'raids_Empty_2', 'raids_successful_2',
       'raids_total_2', 'raids_unsuccessful_2', 'tackles_successful_2',
       'tackles_total_2', 'tackles_unsuccessful_2']].copy()

In [624]:
final_df.head(2)
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 549 entries, 0 to 630
Data columns (total 42 columns):
Team1                                   549 non-null object
Team2                                   549 non-null object
winners                                 549 non-null object
winning_margin                          549 non-null object
all_outs_1                              549 non-null float64
declare_1                               549 non-null float64
points_all_out_1                        549 non-null float64
points_declare_1                        549 non-null float64
points_extras_1                         549 non-null float64
points_raid_points_raid_bonus_1         549 non-null float64
points_raid_points_total_1              549 non-null float64
points_raid_points_touch_1              549 non-null float64
points_tackle_points_capture_1          549 non-null float64
points_tackle_points_capture_bonus_1    549 non-null float64
points_tackle_points_total_1            549 non-null float64
points_total_1                          549 non-null float64
raids_Empty_1                           549 non-null float64
raids_successful_1                      549 non-null float64
raids_total_1                           549 non-null float64
raids_unsuccessful_1                    549 non-null float64
tackles_successful_1                    549 non-null float64
tackles_total_1                         549 non-null float64
tackles_unsuccessful_1                  549 non-null float64
all_outs_2                              549 non-null float64
declare_2                               549 non-null float64
points_all_out_2                        549 non-null float64
points_declare_2                        549 non-null float64
points_extras_2                         549 non-null float64
points_raid_points_raid_bonus_2         549 non-null float64
points_raid_points_total_2              549 non-null float64
points_raid_points_touch_2              549 non-null float64
points_tackle_points_capture_2          549 non-null float64
points_tackle_points_capture_bonus_2    549 non-null float64
points_tackle_points_total_2            549 non-null float64
points_total_2                          549 non-null float64
raids_Empty_2                           549 non-null float64
raids_successful_2                      549 non-null float64
raids_total_2                           549 non-null float64
raids_unsuccessful_2                    549 non-null float64
tackles_successful_2                    549 non-null float64
tackles_total_2                         549 non-null float64
tackles_unsuccessful_2                  549 non-null float64
dtypes: float64(38), object(4)
memory usage: 184.4+ KB

In [625]:
mw=final_df.copy()

In [626]:
mw['winning_margin']=mw['winning_margin'].str.split(" ").str[0]
mw['winning_margin']=mw['winning_margin'].astype('int')

In [627]:
mw.head(2)

,Team1,Team2,winners,winning_margin,all_outs_1,declare_1,points_all_out_1,points_declare_1,points_extras_1,points_raid_points_raid_bonus_1,...,points_tackle_points_capture_bonus_2,points_tackle_points_total_2,points_total_2,raids_Empty_2,raids_successful_2,raids_total_2,raids_unsuccessful_2,tackles_successful_2,tackles_total_2,tackles_unsuccessful_2
0,U Mumba,Jaipur Pink Panthers,U Mumba,14,2.0,0.0,2.0,0.0,0.0,3.0,...,0.0,12.0,44.0,15.0,21.0,40.0,4.0,10.0,32.0,22.0
1,Dabang Delhi K.C.,Bengaluru Bulls,Bengaluru Bulls,19,6.0,0.0,6.0,0.0,0.0,1.0,...,0.0,13.0,28.0,10.0,14.0,41.0,17.0,11.0,33.0,22.0

In [628]:
mw['Winner']=np.where(mw['winners']==mw['Team1'], 1, 0)

In [629]:
mw.drop('winners',axis=1,inplace=True)

In [630]:
mw.head(2)

,Team1,Team2,winning_margin,all_outs_1,declare_1,points_all_out_1,points_declare_1,points_extras_1,points_raid_points_raid_bonus_1,points_raid_points_total_1,...,points_tackle_points_total_2,points_total_2,raids_Empty_2,raids_successful_2,raids_total_2,raids_unsuccessful_2,tackles_successful_2,tackles_total_2,tackles_unsuccessful_2,Winner
0,U Mumba,Jaipur Pink Panthers,14,2.0,0.0,2.0,0.0,0.0,3.0,25.0,...,12.0,44.0,15.0,21.0,40.0,4.0,10.0,32.0,22.0,1
1,Dabang Delhi K.C.,Bengaluru Bulls,19,6.0,0.0,6.0,0.0,0.0,1.0,23.0,...,13.0,28.0,10.0,14.0,41.0,17.0,11.0,33.0,22.0,0

In [631]:
dummy_vars = pd.get_dummies(mw[['Team1','Team2']], drop_first=True)
dummy_vars.head()

,Team1_Bengaluru Bulls,Team1_Dabang Delhi K.C.,Team1_Gujarat Fortunegiants,Team1_Haryana Steelers,Team1_Jaipur Pink Panthers,Team1_Patna Pirates,Team1_Puneri Paltan,Team1_Tamil Thalaivas,Team1_Telugu Titans,Team1_U Mumba,...,Team2_Dabang Delhi K.C.,Team2_Gujarat Fortunegiants,Team2_Haryana Steelers,Team2_Jaipur Pink Panthers,Team2_Patna Pirates,Team2_Puneri Paltan,Team2_Tamil Thalaivas,Team2_Telugu Titans,Team2_U Mumba,Team2_U.P. Yoddha
0,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [632]:
mw = pd.concat([mw, dummy_vars], axis=1)
mw = mw.drop(['Team1','Team2'], axis = 1)

In [633]:
mw.shape
mw.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 549 entries, 0 to 630
Data columns (total 62 columns):
winning_margin                          549 non-null int32
all_outs_1                              549 non-null float64
declare_1                               549 non-null float64
points_all_out_1                        549 non-null float64
points_declare_1                        549 non-null float64
points_extras_1                         549 non-null float64
points_raid_points_raid_bonus_1         549 non-null float64
points_raid_points_total_1              549 non-null float64
points_raid_points_touch_1              549 non-null float64
points_tackle_points_capture_1          549 non-null float64
points_tackle_points_capture_bonus_1    549 non-null float64
points_tackle_points_total_1            549 non-null float64
points_total_1                          549 non-null float64
raids_Empty_1                           549 non-null float64
raids_successful_1                      549 non-null float64
raids_total_1                           549 non-null float64
raids_unsuccessful_1                    549 non-null float64
tackles_successful_1                    549 non-null float64
tackles_total_1                         549 non-null float64
tackles_unsuccessful_1                  549 non-null float64
all_outs_2                              549 non-null float64
declare_2                               549 non-null float64
points_all_out_2                        549 non-null float64
points_declare_2                        549 non-null float64
points_extras_2                         549 non-null float64
points_raid_points_raid_bonus_2         549 non-null float64
points_raid_points_total_2              549 non-null float64
points_raid_points_touch_2              549 non-null float64
points_tackle_points_capture_2          549 non-null float64
points_tackle_points_capture_bonus_2    549 non-null float64
points_tackle_points_total_2            549 non-null float64
points_total_2                          549 non-null float64
raids_Empty_2                           549 non-null float64
raids_successful_2                      549 non-null float64
raids_total_2                           549 non-null float64
raids_unsuccessful_2                    549 non-null float64
tackles_successful_2                    549 non-null float64
tackles_total_2                         549 non-null float64
tackles_unsuccessful_2                  549 non-null float64
Winner                                  549 non-null int32
Team1_Bengaluru Bulls                   549 non-null uint8
Team1_Dabang Delhi K.C.                 549 non-null uint8
Team1_Gujarat Fortunegiants             549 non-null uint8
Team1_Haryana Steelers                  549 non-null uint8
Team1_Jaipur Pink Panthers              549 non-null uint8
Team1_Patna Pirates                     549 non-null uint8
Team1_Puneri Paltan                     549 non-null uint8
Team1_Tamil Thalaivas                   549 non-null uint8
Team1_Telugu Titans                     549 non-null uint8
Team1_U Mumba                           549 non-null uint8
Team1_U.P. Yoddha                       549 non-null uint8
Team2_Bengaluru Bulls                   549 non-null uint8
Team2_Dabang Delhi K.C.                 549 non-null uint8
Team2_Gujarat Fortunegiants             549 non-null uint8
Team2_Haryana Steelers                  549 non-null uint8
Team2_Jaipur Pink Panthers              549 non-null uint8
Team2_Patna Pirates                     549 non-null uint8
Team2_Puneri Paltan                     549 non-null uint8
Team2_Tamil Thalaivas                   549 non-null uint8
Team2_Telugu Titans                     549 non-null uint8
Team2_U Mumba                           549 non-null uint8
Team2_U.P. Yoddha                       549 non-null uint8
dtypes: float64(38), int32(2), uint8(22)
memory usage: 183.4 KB

## Data Preparation

In [634]:
from sklearn.model_selection import train_test_split

X = mw.drop(['Winner'], axis=1)
y = mw["Winner"]
# Separate train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, test_size = 0.3, random_state =100)

In [635]:
cols=X_train.select_dtypes(include=['float64', 'int32']).columns

In [636]:
X_train.head()

,winning_margin,all_outs_1,declare_1,points_all_out_1,points_declare_1,points_extras_1,points_raid_points_raid_bonus_1,points_raid_points_total_1,points_raid_points_touch_1,points_tackle_points_capture_1,...,Team2_Dabang Delhi K.C.,Team2_Gujarat Fortunegiants,Team2_Haryana Steelers,Team2_Jaipur Pink Panthers,Team2_Patna Pirates,Team2_Puneri Paltan,Team2_Tamil Thalaivas,Team2_Telugu Titans,Team2_U Mumba,Team2_U.P. Yoddha
416,21,0.0,0.0,0.0,0.0,2.0,10.0,24.0,14.0,6.0,...,0,0,0,0,0,0,0,1,0,0
52,2,2.0,0.0,2.0,0.0,0.0,3.0,20.0,17.0,6.0,...,0,0,0,0,1,0,0,0,0,0
56,20,6.0,0.0,6.0,0.0,0.0,1.0,16.0,15.0,14.0,...,0,0,0,0,1,0,0,0,0,0
422,9,2.0,0.0,4.0,0.0,2.0,0.0,11.0,11.0,14.0,...,0,0,0,0,0,1,0,0,0,0
20,10,6.0,0.0,6.0,0.0,0.0,3.0,26.0,23.0,13.0,...,0,0,0,0,0,0,0,0,0,0

In [637]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

X_train[cols] = scaler.fit_transform(X_train[cols])

X_train.head(2)

,winning_margin,all_outs_1,declare_1,points_all_out_1,points_declare_1,points_extras_1,points_raid_points_raid_bonus_1,points_raid_points_total_1,points_raid_points_touch_1,points_tackle_points_capture_1,...,Team2_Dabang Delhi K.C.,Team2_Gujarat Fortunegiants,Team2_Haryana Steelers,Team2_Jaipur Pink Panthers,Team2_Patna Pirates,Team2_Puneri Paltan,Team2_Tamil Thalaivas,Team2_Telugu Titans,Team2_U Mumba,Team2_U.P. Yoddha
416,0.512821,0.000000,0.0,0.0,0.0,0.285714,0.769231,0.487179,0.305556,0.277778,...,0,0,0,0,0,0,0,1,0,0
52,0.025641,0.333333,0.0,0.2,0.0,0.000000,0.230769,0.384615,0.388889,0.277778,...,0,0,0,0,1,0,0,0,0,0

---

In [638]:
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor
# ## Logistic regression model
# logm1 = sm.GLM(y_train,(sm.add_constant(X_train)), family = sm.families.Binomial())
# logm1.fit().summary()
from sklearn.linear_model import LogisticRegression
from sklearn.feature_selection import RFE

## Logistic regression model
logreg = LogisticRegression()

## Run RFE to get important features
rfe = RFE(logreg, 10)             
rfe = rfe.fit(X_train, y_train)

X_train.columns[rfe.support_]

### <font color='#008abc'>Building model using statsmodel, for the detailed statistics</font>

# Creating X_train dataframe with RFE selected variables
col=X_train.columns[rfe.support_]
X_train_rfe = X_train[X_train.columns[rfe.support_]]

X_train_rfe.head(1)

,points_all_out_1,points_tackle_points_capture_1,points_tackle_points_total_1,points_total_1,raids_unsuccessful_1,points_raid_points_touch_2,points_tackle_points_total_2,points_total_2,raids_unsuccessful_2,tackles_successful_2
416,0.0,0.277778,0.263158,0.350877,0.833333,0.5,0.882353,0.730769,0.277778,0.777778

In [639]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=100, max_depth=20,
                              random_state=0)
rf.fit(X_train_rfe, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=20, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [640]:
X_test[cols] = scaler.transform(X_test[cols])
X_test_rfe = X_test[X_test.columns[rfe.support_]]

In [641]:
score = rf.score(X_train_rfe, y_train)
score2 = rf.score(X_test_rfe, y_test)

In [642]:
print(score,score2)

1.0 0.8666666666666667

In [643]:
## Current Positions
seasons={ 0:'https://www.prokabaddi.com/sifeeds/kabaddi/live/json/49_standing.json'}

## Fectch all stats data, top 5 teams across various statistics
rows=[]
for key,value in seasons.items():
    print(key,value)
    # Dict of all stats
    data = requests.get(value).json()
    season=key
    for i in data['standings']['groups']:
        for j in i['teams']['team']:
            for k,v in j.items():
                team_name=j['team_name']
                position=j['position']
            rows.append([team_name,position])

        
cols=['team_name','position'] 
team_stats_df = pd.DataFrame(rows, columns=cols)

team_stats_df

0 https://www.prokabaddi.com/sifeeds/kabaddi/live/json/49_standing.json

                team_name position
0       Dabang Delhi K.C.        1
1         Bengal Warriors        2
2        Haryana Steelers        3
3                 U Mumba        4
4         Bengaluru Bulls        5
5             U.P. Yoddha        6
6    Jaipur Pink Panthers        7
7   Gujarat Fortunegiants        8
8           Puneri Paltan        9
9           Patna Pirates       10
10          Telugu Titans       11
11        Tamil Thalaivas       12